version: "3.4"

services:
  UploadFile.Minio:
    container_name: uploadFile.Minio
    image: minio/minio:latest
    environment:
        MINIO_ACCESS_KEY: change-me-to-your-access-key-here
        MINIO_SECRET_KEY: change-me-dont-use-this-for-real
    ports:
        - 9000:9000
    command: server /data
    restart: always
