version: "3.4"

services:
  UploadFile.Api:
    container_name: uploadFile.Api
    build:
      context: .
      dockerfile: ./UploadFile.Api/Dockerfile
    restart: always
    environment:
      ASPNETCORE_APPREQUIREHOST: "*:5000"
      ASPNETCORE_URLS: "http://*:5000"
      ASPNETCORE_ENVIRONMENT: "Development"
      MinioConnectionString: "UploadFile.Minio:9000"
    ports:
      - 5000:5000
    depends_on:
      - UploadFile.Minio
  UploadFile.Minio:
    container_name: uploadFile.Minio
    image: minio/minio:latest
    environment:
        MINIO_ACCESS_KEY: change-me-to-your-access-key-here
        MINIO_SECRET_KEY: change-me-dont-use-this-for-real
    ports:
        - 9000:9000
    command: server /data
    restart: always
